apiVersion: v1
kind: ConfigMap
metadata:
  name: paymentconsumer-config
  namespace: default
  labels:
    app: paymentconsumer
    app.kubernetes.io/name: paymentconsumer
    app.kubernetes.io/component: config
data:
  SERVER_PORT: "8082"
  BENEFICIARIES_SERVICE_URL: "http://localhost:8080"
  PAYMENT_PROCESSOR_SERVICE_URL: "http://localhost:8081"
  HEALTH_DETAILS: "always"
  LOG_LEVEL_ROOT: "INFO"
  LOG_LEVEL_APP: "INFO"
  LOG_LEVEL_JDBC: "INFO"
  HIBERNATE_DDL_AUTO: "update"
  TIMEZONE: "UTC"
