apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paymentconsumer-db-pvc
  namespace: default
  labels:
    app: paymentconsumer
    app.kubernetes.io/name: paymentconsumer
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
