apiVersion: v1
kind: Secret
metadata:
  name: beneficiaries-secret
  namespace: default
  labels:
    app: beneficiaries
    app.kubernetes.io/name: beneficiaries
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "beneficiaries"
  REDIS_PASSWORD: "KFG8g4c6zxM2ElQRDl13pNT1T"
