apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beneficiaries-db-pvc
  namespace: default
  labels:
    app: beneficiaries
    app.kubernetes.io/name: beneficiaries
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
