apiVersion: v1
kind: Secret
metadata:
  name: paymentprocessor-secret
  namespace: default
  labels:
    app: paymentprocessor
    app.kubernetes.io/name: paymentprocessor
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "paymentprocessor"
